### ISSUE TITLE
滤波器复杂度

### ISSUE THREAD

**Issue by OrangeBaoWang** [chenwj1989/MLSP#1]
FBLMS计算复杂度比 BLMS复杂度还要高吗   ？

LMS: 2M+1次乘法和 2M次加法
FBLMS：10M\log M+26M

**Comment by chenwj1989** [comment]
LMS: 2M+1次乘法和 2M次加法是一个点的计算量
对一个block M点序列，复杂度分别为：
LMS ： O(M*M)
FBLMS： O(M *log M)
